apiVersion: v1
kind: Service
metadata:
  name: mint-ui
  namespace: develop
  labels:
    app: mint-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: mint-ui
