kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-develop
  namespace: develop
subjects:
  - kind: ServiceAccount
    name: cicd-develop
    namespace: develop
roleRef:
  kind: Role
  name: cicd-develop
  apiGroup: rbac.authorization.k8s.io
