apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  name: do-kubernetes-sample-app-ingress
spec:
  tls:
  - hosts:
    - test2.mosorio.dev
    secretName: test2_mosorio
  rules:
  - host: test2.mosorio.dev
    http:
      paths:
      - backend:
          serviceName: do-kubernetes-sample-app
          servicePort: 80
