apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: mint-ui-ingress
spec:
  tls:
  - hosts:
    - mint.a.mosorio.dev
    secretName: mint-a-tls
  rules:
  - host: mint.a.mosorio.dev
    http:
      paths:
      - backend:
          serviceName: mint-ui
          servicePort: 80
